### PR TITLE
Fix main build

### LINKED ISSUE #482: Nightly build
<a href="https://github.com/signalfx/splunk-otel-java/actions/runs/1299825266">
Nightly build #52</a> failed. Please take a look and fix it ASAP.

### LINKED ISSUE #483: Nightly build
<a href="https://github.com/signalfx/splunk-otel-java/actions/runs/1302283463">
Nightly build #53</a> failed. Please take a look and fix it ASAP.

### LINKED ISSUE #484: Nightly build
<a href="https://github.com/signalfx/splunk-otel-java/actions/runs/1302283463">
Nightly build #53</a> failed. Please take a look and fix it ASAP.

### PR DESCRIPTION
**Pull request by mateuszrzeszutek**
Fixes #482 
Fixes #483 
Fixes #484

### CODE REVIEW

**Review by laurit — APPROVED** [review]

**Review by kubawach — APPROVED** [review]

**Review by iNikem — APPROVED** [review]

File: smoke-tests/src/test/java/com/splunk/opentelemetry/AppServerTest.java [hunk 1]
```diff
@@ -27,11 +25,7 @@
 import com.splunk.opentelemetry.helper.TestImage;
 import io.opentelemetry.proto.trace.v1.Span;
 import java.io.IOException;
-import java.util.ArrayList;
-import java.util.Arrays;
-import java.util.Collections;
-import java.util.List;
-import java.util.Set;
+import java.util.*;
```
Comment (laurit) [inline smoke-tests/src/test/java/com/splunk/opentelemetry/AppServerTest.java:28]: Did you accidentally change it to use wildcard imports?

Comment (mateuszrzeszutek) [reply smoke-tests/src/test/java/com/splunk/opentelemetry/AppServerTest.java]: Hmm, it must have happened when I reset IntelliJ settings around the time groovy code formatting in the upstream repo was changed. Thanks for catching this!
