### PR TITLE
[profiler] Log export errors at most once per hour

### LINKED ISSUE #566: Profiler only logs collector connectivity issues as DEBUG
This came up in a customer troubleshooting session. No data was coming to the collector, but no errors were displayed in the agent logs. After debug logs were turned on via `-Dotel.javaagent.debug=true`, the problem became clear. As it turned out, the endpoint was specified as `https://localhost:4317` (note the protocol)

```
Caused by: io.grpc.netty.shaded.io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 000006040000000000000500004000
```

To make future troubleshooting faster, this sort of errors should be logged at the WARN level. To avoid polluting the logs too much, consider logging it just once per run or per hour. We should also very non-ambiguously mark the log messages as coming from the Splunk Java Agent, not from the instrumented application itself.

### PR DESCRIPTION
**Pull request by breedx-splk**
Resolves #566

### CODE REVIEW

File: profiler/src/main/java/com/splunk/opentelemetry/logs/OtlpLogsExporter.java [hunk 1]
```diff
@@ -79,7 +87,31 @@ public void onSuccess(@Nullable ExportLogsServiceResponse result) {
...
     public void onFailure(Throwable th) {
-      logger.debug("Failed to export logs", th);
+      errorLogger.log("Splunk profiling agent failed to export logs", th);
+    }
+  }
+
+  @VisibleForTesting
+  static class OncePerHourLogger {
+    private final AtomicReference<Instant> lastErrorTime = new AtomicReference<>(Instant.EPOCH);
+    private final Supplier<Instant> clock;
```
Comment (mateuszrzeszutek) [inline profiler/src/main/java/com/splunk/opentelemetry/logs/OtlpLogsExporter.java:97]: You can just use `Clock` instead - and call `clock.instant()`

**Review by mateuszrzeszutek — APPROVED** [review]

File: profiler/src/main/java/com/splunk/opentelemetry/logs/OtlpLogsExporter.java [hunk 2]
```diff
@@ -79,7 +87,31 @@ public void onSuccess(@Nullable ExportLogsServiceResponse result) {
 
     @Override
     public void onFailure(Throwable th) {
-      logger.debug("Failed to export logs", th);
+      errorLogger.log("Splunk profiling agent failed to export logs", th);
```
Comment (laurit) [inline profiler/src/main/java/com/splunk/opentelemetry/logs/OtlpLogsExporter.java:90]: In my opinion logging this with warn or error is enough, no need to bother with logging once an hour. Firstly isn't this class going to be replaced with logs exporter from otel? If so then all changes here would be lost when the switch happens. Secondly exporting logs should not be special cased. If exporting traces and metrics logs failures on every export then, for consistency, exporting logs should behave the same way or the same changes should be made to all exporters. Thirdly if there are intermittent failures this will allow logging such failure only once an hour, which would be confusing.

Comment (breedx-splk) [reply profiler/src/main/java/com/splunk/opentelemetry/logs/OtlpLogsExporter.java:90]: Yeah, this is a valid point. I tried to point this out this same thing in #566. 
@gsmirnov-splk what do you think?

Comment (gsmirnov-splk) [reply profiler/src/main/java/com/splunk/opentelemetry/logs/OtlpLogsExporter.java:90]: I do not have a strong opinion here. I only suggested logging once per hour/per run because there were prior verbosity concerns cited.

Comment (breedx-splk) [reply profiler/src/main/java/com/splunk/opentelemetry/logs/OtlpLogsExporter.java]: Ok, well I'm in favor of simpler/less code, so I'll just remove all the time-based guarding and just log at warn. We can relax it when folks complain.

**Review by laurit — APPROVED** [review]
